spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    open-in-view: false
  stripe:
    secret: ${STRIPE_SECRET_KEY}
